from typing import Protocol

from backend.app.domain.models import (
    Article,
    Document,
    DocumentChunk,
    IngestionJob,
    KnowledgeBase,
    KnowledgeBaseMember,
    KnowledgePage,
    KnowledgeSection,
    RagChunk,
    User,
    UserCredentials,
)


class UserRepository(Protocol):
    def get_user_by_id(self, user_id: str) -> User | None: ...

    def get_user_by_session_token(self, token: str) -> User | None: ...

    def get_user_credentials_by_email(self, email: str) -> UserCredentials | None: ...

    def get_user_credentials_by_role(self, role: str) -> UserCredentials | None: ...

    def create_user_session(self, user_id: str) -> str: ...

    def create_user(self, user: UserCredentials) -> UserCredentials: ...

    def delete_user_session(self, token: str) -> bool: ...


class ArticleRepository(Protocol):
    def list_articles(self) -> list[Article]: ...

    def get_article_by_id(self, article_id: str) -> Article | None: ...

    def save_article(self, article: Article) -> Article: ...

    def delete_article(self, article_id: str) -> bool: ...


class DocumentRepository(Protocol):
    def list_documents(self, knowledge_base_id: str | None = None) -> list[Document]: ...

    def get_document_by_id(self, document_id: str) -> Document | None: ...

    def create_document(self, document: Document) -> Document: ...

    def update_document_status(self, document_id: str, status: str) -> Document | None: ...

    def update_document_metadata(self, document_id: str, metadata: dict[str, object]) -> Document | None: ...

    def list_ingestion_jobs(self, document_id: str | None = None) -> list[IngestionJob]: ...

    def create_ingestion_job(self, job: IngestionJob) -> IngestionJob: ...

    def update_ingestion_job_status(
        self,
        job_id: str,
        status: str,
        *,
        error: str | None = None,
        started_at: str | None = None,
        finished_at: str | None = None,
    ) -> IngestionJob | None: ...

    def replace_document_chunks(self, document_id: str, chunks: list[DocumentChunk]) -> list[DocumentChunk]: ...

    def list_document_chunks(self) -> list[DocumentChunk]: ...


class KnowledgeBaseRepository(Protocol):
    def list_knowledge_bases(self, user: User) -> list[KnowledgeBase]: ...

    def get_knowledge_base(self, base_id: str) -> KnowledgeBase | None: ...

    def create_knowledge_base(self, base: KnowledgeBase) -> KnowledgeBase: ...

    def add_knowledge_base_member(self, member: KnowledgeBaseMember) -> KnowledgeBaseMember: ...

    def update_knowledge_base_member_role(
        self,
        base_id: str,
        user_id: str,
        role: str,
        updated_at: str,
    ) -> KnowledgeBaseMember | None: ...

    def create_knowledge_section(self, section: KnowledgeSection) -> KnowledgeSection: ...

    def create_knowledge_page(self, page: KnowledgePage) -> KnowledgePage: ...

    def update_knowledge_page(self, page_id: str, payload: dict[str, object]) -> KnowledgePage | None: ...

    def get_knowledge_page(self, page_id: str) -> KnowledgePage | None: ...

    def replace_rag_chunks(self, source_type: str, source_id: str, chunks: list[RagChunk]) -> list[RagChunk]: ...

    def list_rag_chunks(self, knowledge_base_id: str) -> list[RagChunk]: ...

    def create_chat_thread(self, thread: dict[str, object]) -> dict[str, object]: ...

    def get_chat_thread(self, thread_id: str) -> dict[str, object] | None: ...

    def create_chat_message(self, message: dict[str, object]) -> dict[str, object]: ...

    def create_retrieval_trace(self, trace: dict[str, object]) -> dict[str, object]: ...


class KnowledgeRepository(UserRepository, ArticleRepository, DocumentRepository, KnowledgeBaseRepository, Protocol):
    pass
