from typing import Protocol

from backend.app.domain.models import Article, Document, IngestionJob, User, UserCredentials


class UserRepository(Protocol):
    def get_user_by_id(self, user_id: str) -> User | None: ...

    def get_user_by_session_token(self, token: str) -> User | None: ...

    def get_user_credentials_by_email(self, email: str) -> UserCredentials | None: ...

    def get_user_credentials_by_role(self, role: str) -> UserCredentials | None: ...

    def create_user_session(self, user_id: str) -> str: ...

    def delete_user_session(self, token: str) -> bool: ...


class ArticleRepository(Protocol):
    def list_articles(self) -> list[Article]: ...

    def get_article_by_id(self, article_id: str) -> Article | None: ...

    def save_article(self, article: Article) -> Article: ...

    def delete_article(self, article_id: str) -> bool: ...


class DocumentRepository(Protocol):
    def list_documents(self) -> list[Document]: ...

    def create_document(self, document: Document) -> Document: ...

    def update_document_status(self, document_id: str, status: str) -> Document | None: ...

    def list_ingestion_jobs(self, document_id: str | None = None) -> list[IngestionJob]: ...

    def create_ingestion_job(self, job: IngestionJob) -> IngestionJob: ...

    def update_ingestion_job_status(
        self,
        job_id: str,
        status: str,
        *,
        error: str | None = None,
        started_at: str | None = None,
        finished_at: str | None = None,
    ) -> IngestionJob | None: ...


class KnowledgeRepository(UserRepository, ArticleRepository, DocumentRepository, Protocol):
    pass
